# Generated by Django 4.1.3 on 2022-12-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
